### ISSUE TITLE
Howto instructions on adding to Google Docs

### ISSUE THREAD

**Issue by georgegoh** [RedHatOfficial/RedHatFont#17]
We could do with some instructions (or pointers to links) on how to add these fonts to Google Docs.

**Comment by inferno986return** [comment]
I didn't know it was possible to add custom typefaces to Google Docs. 

In the case of IBM Plex I just requested they be added to Google Docs/Sheets/Slides by the developer.

**Comment by santhoshtr** [comment]
Google had added these fonts to Google Fonts. See https://github.com/google/fonts/pull/1931
But they are not deployed at fonts.google.com yet. Once done, you can choose this as one of the font in google docs.

**Comment by starryeyez024** [comment]
We released a [new version of the font today](https://github.com/RedHatOfficial/RedHatFont/releases/tag/2.3.0)  to correct some metadata issues that Google requested. We should see it added to Google Fonts soon.

**Comment by starryeyez024** [comment]
The fonts are available on https://fonts.google.com/?query=red+hat
