### ISSUE TITLE
Commision someone to provide official variable fonts (both Text and Display, but not in the same font)

### ISSUE THREAD

**Issue by cssobral2013** [RedHatOfficial/RedHatFont#28]

**Comment by starryeyez024** [comment]
@cssobral2013  hello, can you please provide a description and steps on how to reproduce the issue you are seeing?

**Comment by cssobral2013** [comment]
Description: As per title, I'm asking if can you comission someone to make a variable version of RedHat font, but NOT in the same font (naturally, with independent weights for Regular and Italic).

How to display this: Just download Red Hat from this repo; there you'll see independent weights (instead of just 4).
This is kinda of an enhancement than a bug.
