### ISSUE TITLE
Quotation marks rendering inconsistency between webfont and .ttf version

### ISSUE THREAD

**Issue by cntlsn** [RedHatOfficial/RedHatFont#32]
I might have found an issue with how quotation marks are rendered in .ttf version of the font (both Red Hat Display and Red Hat Text), if compared to its webfont versions.

Below you can see how quotation marks (both single and double) are rendered **straight** in a browser -- font is inherited from PatternFly `"@patternfly/react-core": "^3.124.1", "@patternfly/react-styles": "^3.6.11",` and browser is Chrome `79.0.3945.79` on a machine running macOS Mojave:
<img width="603" alt="Screenshot 2019-12-17 18 38 20" src="https://user-images.githubusercontent.com/2865173/71020371-754c3f00-20fc-11ea-9d46-2a2a725c176e.png">

Whereas below you can see how quotation marks for the same font family are rendered **slanted** in Illustrator `24.0` (same in Sketch `61 (89581)`):
<img width="670" alt="Screenshot 2019-12-17 18 39 45" src="https://user-images.githubusercontent.com/2865173/71020435-9ad94880-20fc-11ea-954b-8c925dcbc020.png">

According to a conversation with Red Hat UXD content strategist @abigaeljamie the latter could eventually be misinterpreted for backquotes (https://www.computerhope.com/jargon/b/backquot.htm).

**Comment by jeremymickel** [comment]
This is an Adobe feature called ‘Typographer Quotes’, and is not unique to
Red Hat.

If you turn it off in Illustrator preferences you’ll have the regular
straight quotes.

**Comment by cntlsn** [comment]
Hi @jeremymickel, thank you for the lead. I did a bit of research and apparently it's a system setting (at least on macOS).

It can be solved in two ways:
1. Disable globally -- System Preferences › Keyboard › Text › Use Smart Quotes
2. Disable on a case by case basis -- Right click (on selected quote) > Substitutions > Smart quotes (untick) > Type quotes again

Source: https://twitter.com/sketch/status/476354062225776640?lang=en
