### ISSUE TITLE
Offensive Problematic Terms used throughout this repo and others

### ISSUE THREAD

**Issue by SimonThunderhawk** [RedHatOfficial/RedHatFont#46]
Hello, I noted your CTO's [commitment to removing Problematic Language](https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language) from your company's software.  As a Native American, I find the term "Red Hat" offensive, it brings to mind the stereotypes of my people, "red men" in racist parlance, and this sadly still exists, the term "Red Hat" sounds like a racist depiction of a giant feathered headdress the type often used to mock Native peoples..  The term "red" has been used to disparage Native Americans for centuries, leading to the ongoing genocide against our people.  It is a very problematic, racist term.

Please, if you want to be an ally please at the very least change all instances of the word "Red" including in your company name, to "Native American".  
Instead of "RedHatOfficial" it should be "NativeAmericanHatOfficial"
Instead of "RedHatFont" it should be "NativeAmericanHatFont"
You should also change the NativeAmericanHat logo to be something that better represents Native Americans, something that properly represents the land your company was founded on, a land rightfully and forever owned by the Native Americans tribes who have lived here since the beforetime.
Alternatively, you could change your company name and repositories entirely to something that isn't racist.  Your choice.  But the status quo is unacceptable.

Yours truly,
Simon Thunderhawk

**Comment by kenmcd** [comment]
Wow. And I thought the "Red" in "Red Hat" was just the color of the hat in the logo.
Red dye no. 5 - also clearly racist.
ROYGBIV - racist code, but we all know the true meaning.
Little Red Riding Hood - clearly cultural appropriation, and racist.
Other problematic color references.
"Black as night" - clearly racist.
"White Knight" - clearly a reference to white supremacy, and racist.
"Yellow Fever" - clearly racist.
"Orange Man" - clearly associated with racism. 
"Blue Moon" - people who identify as "blue" should be deeply offended.
OMG, it's everywhere. 
Colors are clearly racist and should be eliminated at once.

**Comment by bproffitt** [comment]
This issue was closed due to lack of relevance to the project.
