### ISSUE TITLE
README could do with an image or two of the fonts

### ISSUE THREAD

**Issue by RalphCorderoy** [RedHatOfficial/RedHatFont#8]
There might be more take up of the fonts if visiting https://github.com/RedHatOfficial/RedHatFont#readme showed an image or two of the fonts. That's a lot lower overhead than having to download, install, and switch to them.

**Comment by webknjaz** [comment]
Alternatively, it could be nice to have a web-page on gh-pages for that...

**Comment by bomberstudios** [comment]
Just opened a PR that fixes this, hope it can be merged soon 🤞
